config/routes.rb
Rails.application.routes.draw do

  resources :post do
    member do
      get 'like'
    end
  end

  resources :comment, only: :create

  root :to => 'post#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to :back,notice: 'コメントしました！'
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

end

app/controllers/post_controller.rb
class PostController < ApplicationController

  def index
    @post = Post.new
    @posts = Post.all
  end

  def create
    @post = Post.create(post_params)
    redirect_to post_index_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def like
    @post = Post.find(params[:id])
    @post.increment(:like)
    @post.save
    redirect_to :back, notice: 'いいねしました！'
  end

  private
    def post_params
      params.require(:post).permit(:content, :like)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SummerIntrenTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/index.html.erb
<h1>Mini blog</h1>

<p><%=notice %></p>

<%= form_for @post, :url => {:action => :create} do |f| %>
    <div class='field'>
      <%= f.text_field :content %>
      <%= f.hidden_field :like, value: 0 %>
      <%= f.submit %>
    </div>
<% end %>

<% @posts.order('id').reverse_each do |post| %>
    <p><%= post.id%>:<%= link_to post.content, post_path(post) %></p>
    <p><%= link_to 'いいね', like_post_path(post)%>:<%= post.like %>| コメント数:<%=post.comments.count%>| 投稿日時:<%= post.created_at.to_s(:created_at) %></p>
<% end %>

app/views/post/show.html.erb
<h1>Mini blog</h1>
<p><%=notice %></p>
<%= link_to '戻る',post_index_path %>

<p><%= @post.id %>:投稿日時:<%= @post.created_at.to_s(:created_at) %>|<%= link_to 'いいね', like_post_path(@post)%>:<%= @post.like %></p>
<p><%= @post.content %></p>

  <%= form_for @comment, :url =>{ :controller => :comment, :action => :create } do |f| %>
    <div class='field'>
      <%= f.text_field :content %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%= f.submit %>
    </div>
<% end %>

<% if @comments.nil?%>
  <p>コメントはありません。</p>
<% else %>
  <% @comments.each do |comment| %>
    <p><%= comment.content %>  | 投稿日時:<%= comment.created_at.to_s(:created_at) %></p>
  <% end %>
<% end %>